#!/bin/bash

chosen=$(printf "Enable Redshift\nDisable Redshift\nTemp 4500K\nTemp 5000K\nTemp 5500K\nTemp 6000K\nReset" | rofi -dmenu -p "Redshift" -theme ~/.config/i3/redshift/redshift.rasi)

case "$chosen" in
  "Enable Redshift") redshift -x && redshift -O 5000 ;;
  "Disable Redshift") redshift -x ;;
  "Temp 4500K") redshift -x && redshift -O 4500 ;;
  "Temp 5000K") redshift -x && redshift -O 5000 ;;
  "Temp 5500K") redshift -x && redshift -O 5500 ;;
  "Temp 6000K") redshift -x && redshift -O 6000 ;;
  "Reset") redshift -x ;;
esac
